FROM node:14-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ADD .eslintrc.json /usr/src/app/.eslintrc.json
ADD package.json /usr/src/app/package.json
ADD package-lock.json /usr/src/app/package-lock.json
ADD env.sh /usr/src/app/env.sh
ADD .env /usr/src/app/.env
COPY public /usr/src/app/public
COPY src /usr/src/app/src

RUN npm config set unsafe-perm true
RUN npm install --silent
RUN npm install react-scripts -g --silent

RUN apk add --no-cache bash
RUN chmod +x /usr/src/app/env.sh

EXPOSE 3000
CMD ["npm", "run", "dev"]
